# Generated by Django 5.0.4 on 2024-04-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='safetyalert',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='safetyalert',
            name='sensor_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='safetyalert',
            name='sensor_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safetyalert',
            name='severity_level',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Low')], default='LOW', max_length=10),
        ),
    ]
