# Generated by Django 5.0.4 on 2024-04-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='asset',
        ),
        migrations.DeleteModel(
            name='ComplianceCheck',
        ),
        migrations.DeleteModel(
            name='Regulation',
        ),
        migrations.DeleteModel(
            name='Maintenance',
        ),
    ]
