# Generated by Django 5.0.4 on 2024-04-27 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0004_anomalydetection_datamining_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnomalyDetection',
        ),
        migrations.DeleteModel(
            name='DataMining',
        ),
        migrations.DeleteModel(
            name='NaturalLanguageProcessing',
        ),
        migrations.DeleteModel(
            name='PredictiveMaintenance',
        ),
        migrations.DeleteModel(
            name='RiskPrediction',
        ),
    ]
