# Generated by Django 5.0.4 on 2024-04-29 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0006_person_accesslog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessLog',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
