# Generated by Django 5.0.4 on 2024-04-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alert_customizablereport_regulatoryupdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMiningAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=100)),
                ('algorithm_name', models.CharField(max_length=100)),
                ('insights', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FacialRecognitionAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('access_granted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='IncidentPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_description', models.TextField()),
                ('likelihood', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NaturalLanguageProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('interpretation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OptimizationAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimization_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PatternRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RiskPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_description', models.TextField()),
                ('likelihood', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('sentiment', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='RiskAssessment',
            new_name='AutomatedComplianceCheck',
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='CustomizableReport',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='maintenancereminder',
            name='equipment',
        ),
        migrations.DeleteModel(
            name='RegulatoryUpdate',
        ),
        migrations.DeleteModel(
            name='TrainingResource',
        ),
        migrations.RenameField(
            model_name='automatedcompliancecheck',
            old_name='description',
            new_name='compliance_check_description',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='MaintenanceReminder',
        ),
    ]
