# Generated by Django 5.0.4 on 2024-04-27 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dataminingalgorithm_facialrecognitionaccess_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutomatedComplianceCheck',
        ),
        migrations.DeleteModel(
            name='DataMiningAlgorithm',
        ),
        migrations.DeleteModel(
            name='FacialRecognitionAccess',
        ),
        migrations.DeleteModel(
            name='IncidentPrediction',
        ),
        migrations.DeleteModel(
            name='NaturalLanguageProcessing',
        ),
        migrations.DeleteModel(
            name='OptimizationAlgorithm',
        ),
        migrations.DeleteModel(
            name='PatternRecognition',
        ),
        migrations.DeleteModel(
            name='RiskPrediction',
        ),
        migrations.DeleteModel(
            name='SentimentAnalysis',
        ),
    ]
