# Generated by Django 5.0.4 on 2024-04-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidrivensafetymanagement',
            name='chart_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aidrivensafetymanagement',
            name='data_entry',
            field=models.TextField(blank=True, null=True),
        ),
    ]
