# Generated by Django 5.0.4 on 2024-04-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_remove_profile_email_remove_profile_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_photos/'),
        ),
    ]
